# -*- coding: utf-8 -*-
"""table_preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qnenjGBqjJcPWKpNDwvzlfVzrVocRXbJ
"""

import numpy as np
import pandas as pd

def table_preprocessing():
    df = pd.read_csv("hotel_reservations.csv")
    df = df.drop('Booking_ID', axis=1)
    y = df['booking_status']
    X = df.drop('booking_status', axis=1)
    categorical_columns = X.select_dtypes(include='object').columns
    X = pd.get_dummies(X, columns=categorical_columns)
    y = y.map({'Canceled': 1, 'Not_Canceled': 0})

    return X, y

table_preprocessing()