# -*- coding: utf-8 -*-
"""table_preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qnenjGBqjJcPWKpNDwvzlfVzrVocRXbJ
"""

import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import recall_score


def table_preprocessing():
    df = pd.read_csv("hotel_reservations.csv")

    df = df.drop('Booking_ID', axis=1)

    y = df['booking_status']
    X = df.drop('booking_status', axis=1)

    categorical_columns = X.select_dtypes(include='object').columns
    X = pd.get_dummies(X, columns=categorical_columns)

    y = y.map({'Canceled': 1, 'Not_Canceled': 0})

    return X, y


X, y = table_preprocessing()


def hotel_booking_analyse(X, y):

    X_train, X_test, y_train, y_test = train_test_split(
        X, y,
        test_size=0.25,
        stratify=y,
        random_state=42
    )

    scaler = StandardScaler(with_mean=False)

    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled = scaler.transform(X_test)

    lr = LogisticRegression(max_iter=3000)
    dt = DecisionTreeClassifier(random_state=42)
    knn = KNeighborsClassifier()

    lr.fit(X_train_scaled, y_train)
    knn.fit(X_train_scaled, y_train)
    dt.fit(X_train, y_train)

    lr_pred = lr.predict(X_test_scaled)
    knn_pred = knn.predict(X_test_scaled)
    dt_pred = dt.predict(X_test)

    recall_lr = recall_score(y_test, lr_pred)
    recall_knn = recall_score(y_test, knn_pred)
    recall_dt = recall_score(y_test, dt_pred)

    print(f"1) LogisticRegression recall: {round(recall_lr, 3)}")
    print(f"2) KNN recall: {round(recall_knn, 3)}")
    print(f"3) DecisionTree recall: {round(recall_dt, 3)}")

    if recall_lr > recall_knn and recall_lr > recall_dt:
        print("4) Лучший результат: LogisticRegression")
    elif recall_knn > recall_lr and recall_knn > recall_dt:
        print("4) Лучший результат: KNN")
    else:
        print("4) Лучший результат: DecisionTree")


hotel_booking_analyse(X, y)

